import dd = require('./a');
//import { StickPackage } from './a';
import { StickPackage } from './stick';
//let ada = new dd.StickPackage(); 
//StickPackage.prototype.test();
//let pack = new StickPackage();
//console.log(pack.buffer);
let buf = new Buffer(2);
let buf1 = new Buffer(2);
console.log(buf[0]);
console.log(buf1);
// // console.log(buf[0]);
// // console.log(buf[1]);
// pack.push(buf,0,2);